### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by viniciuscnr** [flaviojoliveira/CGPI-estudos#1]
Flávio, não estou encontrando o arquivo que fizemos em conjunto na aula. Devido à um problema de conexão, perdi muita coisa no colab

**Comment by flaviojoliveira** [comment]
Certo. Esta issue foi postada no repositório de Computação Gráfica.

Sugiro que faça um fork dos repositórios IA_estudos as atividades realizadas estão disponíveis lá.

**Comment by flaviojoliveira** [comment]
ok
